export type ReactiveBehaviorProfile = {
  label: 'Chill' | 'Full On'
  bassFloor: number
  bassCurve: number
  kickPulseFloor: number
  kickPulseCurve: number
  sustainedDepthMaxContribution: number
  kickDepthMaxContribution: number
  finalDepthCapContribution: number
  sustainedAttackPerSecond: number
  sustainedReleasePerSecond: number
  kickAttackPerSecond: number
  kickReleasePerSecond: number
  kickEventThreshold: number
  kickEventCooldownMs: number
  kickHueStepDegrees: number
  kickHueVariationDegrees: number
  hueEasingAttackPerSecond: number
  hueEasingReleasePerSecond: number
  ambientDriftScaleWhenReactive: number
  ambientSwayScaleWhenReactive: number
  saturationMaxBoost: number
  globalLightMaxBoost: number
  surfaceGlowMaxBoost: number
  transientGlowMaxBoost: number
  lightingAttackPerSecond: number
  lightingReleasePerSecond: number
  glowAttackPerSecond: number
  glowReleasePerSecond: number
  transientAttackPerSecond: number
  transientReleasePerSecond: number
  fullOnLowDepthTarget: number
  fullOnHighDepthTarget: number
  fullOnRestDepthTarget: number
  fullOnDepthTravelAttackPerSecond: number
  fullOnDepthTravelReleasePerSecond: number
  fullOnKickAmplitudeDepthInfluence: number
  fullOnInactivityTimeoutMs: number
  fullOnInactivityReturnPerSecond: number
  kickBloomAttackPerSecond: number
  kickBloomReleasePerSecond: number
  kickBloomHoldMs: number
  kickSaturationBloomMaxBoost: number
  kickGlobalGlowBloomMaxBoost: number
  kickSurfaceGlowBloomMaxBoost: number
  chillHueDriftRangeDegrees: number
  chillHueDriftCycleSeconds: number
  authoredHueCycleScale: number
  authoredSaturationCycleScale: number
  authoredGlobalGlowCycleScale: number
  authoredSurfaceGlowPeriodicScale: number
  sectionIntensityQuietFloor: number
  sectionIntensityFullLevel: number
  hueEventStride: number
  saturationCap: number
}

export type ReactiveBehaviorId = 'chill' | 'fullon'

export const REACTIVE_BEHAVIOR_PROFILES: Record<ReactiveBehaviorId, ReactiveBehaviorProfile> = {
  chill: {
    label: 'Chill',
    bassFloor: 0.16,
    bassCurve: 1.55,
    kickPulseFloor: 0.08,
    kickPulseCurve: 1,
    sustainedDepthMaxContribution: 0.48,
    kickDepthMaxContribution: 0.56,
    finalDepthCapContribution: 0.98,
    sustainedAttackPerSecond: 4.8,
    sustainedReleasePerSecond: 1.05,
    kickAttackPerSecond: 11.5,
    kickReleasePerSecond: 1.8,
    kickEventThreshold: 0.24,
    kickEventCooldownMs: 220,
    kickHueStepDegrees: 0,
    kickHueVariationDegrees: 0,
    hueEasingAttackPerSecond: 0,
    hueEasingReleasePerSecond: 0,
    ambientDriftScaleWhenReactive: 0.22,
    ambientSwayScaleWhenReactive: 0.13,
    saturationMaxBoost: 0.3,
    globalLightMaxBoost: 0.2,
    surfaceGlowMaxBoost: 0.28,
    transientGlowMaxBoost: 0.19,
    lightingAttackPerSecond: 4.4,
    lightingReleasePerSecond: 1.8,
    glowAttackPerSecond: 5.2,
    glowReleasePerSecond: 2.2,
    transientAttackPerSecond: 11,
    transientReleasePerSecond: 4.4,
    fullOnLowDepthTarget: 0.22,
    fullOnHighDepthTarget: 0.52,
    fullOnRestDepthTarget: 0.26,
    fullOnDepthTravelAttackPerSecond: 5,
    fullOnDepthTravelReleasePerSecond: 2.6,
    fullOnKickAmplitudeDepthInfluence: 0.18,
    fullOnInactivityTimeoutMs: 900,
    fullOnInactivityReturnPerSecond: 1.8,
    kickBloomAttackPerSecond: 7,
    kickBloomReleasePerSecond: 4,
    kickBloomHoldMs: 90,
    kickSaturationBloomMaxBoost: 0.12,
    kickGlobalGlowBloomMaxBoost: 0.12,
    kickSurfaceGlowBloomMaxBoost: 0.12,
    chillHueDriftRangeDegrees: 60,
    chillHueDriftCycleSeconds: 56,
    authoredHueCycleScale: 1,
    authoredSaturationCycleScale: 1,
    authoredGlobalGlowCycleScale: 1,
    authoredSurfaceGlowPeriodicScale: 1,
    sectionIntensityQuietFloor: 0.2,
    sectionIntensityFullLevel: 0.58,
    hueEventStride: 1,
    saturationCap: 2.25,
  },
  fullon: {
    label: 'Full On',
    bassFloor: 0.12,
    bassCurve: 1.45,
    kickPulseFloor: 0.06,
    kickPulseCurve: 0.72,
    sustainedDepthMaxContribution: 0.36,
    kickDepthMaxContribution: 1.06,
    finalDepthCapContribution: 1.35,
    sustainedAttackPerSecond: 5.1,
    sustainedReleasePerSecond: 1.1,
    kickAttackPerSecond: 16,
    kickReleasePerSecond: 3.1,
    kickEventThreshold: 0.19,
    kickEventCooldownMs: 180,
    kickHueStepDegrees: 32,
    kickHueVariationDegrees: 6,
    hueEasingAttackPerSecond: 8,
    hueEasingReleasePerSecond: 1.2,
    ambientDriftScaleWhenReactive: 0.32,
    ambientSwayScaleWhenReactive: 0.16,
    saturationMaxBoost: 0.56,
    globalLightMaxBoost: 0.42,
    surfaceGlowMaxBoost: 0.62,
    transientGlowMaxBoost: 0.28,
    lightingAttackPerSecond: 7.5,
    lightingReleasePerSecond: 2.6,
    glowAttackPerSecond: 9.5,
    glowReleasePerSecond: 3.1,
    transientAttackPerSecond: 13,
    transientReleasePerSecond: 4.6,
    fullOnLowDepthTarget: 0.06,
    fullOnHighDepthTarget: 1.18,
    fullOnRestDepthTarget: 0.1,
    fullOnDepthTravelAttackPerSecond: 17.5,
    fullOnDepthTravelReleasePerSecond: 8.6,
    fullOnKickAmplitudeDepthInfluence: 0.22,
    fullOnInactivityTimeoutMs: 900,
    fullOnInactivityReturnPerSecond: 2.8,
    kickBloomAttackPerSecond: 22,
    kickBloomReleasePerSecond: 4.1,
    kickBloomHoldMs: 130,
    kickSaturationBloomMaxBoost: 0.7,
    kickGlobalGlowBloomMaxBoost: 0.68,
    kickSurfaceGlowBloomMaxBoost: 1.35,
    chillHueDriftRangeDegrees: 0,
    chillHueDriftCycleSeconds: 1,
    authoredHueCycleScale: 0,
    authoredSaturationCycleScale: 0.2,
    authoredGlobalGlowCycleScale: 0.16,
    authoredSurfaceGlowPeriodicScale: 0.42,
    sectionIntensityQuietFloor: 0.2,
    sectionIntensityFullLevel: 0.58,
    hueEventStride: 2,
    saturationCap: 2.38,
  },
}

export const REACTIVE_PREVIEW_PROFILE = REACTIVE_BEHAVIOR_PROFILES.chill
